print("")
print("\u0334".join("LEAGUE OF LEGENDS"))
print("")
print("Username : miZu")
print("")
print("Level : 97")
print("")
print("Top 3 Mastery :")
print("")
print(" 1. Lillia")
print(" 2. Akali")
print(" 3. Lee sin")
